### ISSUE TITLE
The default flashing orange LED is scary!

### ISSUE THREAD

**Issue by lowtolerance** [dx4m/Modern-Xbox-EEPROM-Dumper#1]
I installed this, turned on my Xbox, and started to panic when the LED almost immediately started flashing orange - that’s normally an indication that the system is overheating! I spent a while fretting that I’d somehow spilled some solder on my mobo, then a while longer wondering how an EEPROM reader could cause the system overheat 😂 Finally, it dawned on me that my Xbox was fine. A solid orange LED has no special meaning, maybe that would be preferable?

**Comment by dx4m** [comment]
Hi,

i changed it to an solid orange light. So when you start the console, around 3 seconds it should change to orange.

Have fun with it. 😄

**Comment by Natetronn** [comment]
You sure scared @lowtolerance :joy: 

@dx4m as and aside, I started working on a PyQt GUI for Ryzee119's ArduinoProm code base, which uses an Arduino Micro Pro, if you're familiar with that. It's working but, I got stuck on the RC4 stuff. Looks like you're handling that nicely.

BTW, thanks for all the work on this!

**Comment by lowtolerance** [comment]
Thanks!
