### ISSUE TITLE
Bug in code

### ISSUE THREAD

**Issue by dtomcat** [dx4m/Modern-Xbox-EEPROM-Dumper#4]
Hello,
   Working with this a bit... (only decrypt portion) and I believe there is a bug in the code (xbox_eeprom_utility/xbox_eeprom_utility.ino). 
All of your `if (xbx->decrypt()...` statements compare to >0.  decrypt returns version number.   So your if statement will always fail if working with a rev 1.0 xbox.  Should be >=0.   Sorry if I'm mistaken.  hope this all makes sense. 

For instance:
line 976:  `if (xbx->decrypt(d) > 0) {`
should be `if (xbx->decrypt(d) >= 0) {`

**Comment by wuspy** [comment]
I can reproduce this issue on my 1.0 Xbox as well, it shows version undefined and a zero HDD key. With the changes @dtomcat suggested it loads the correct information.

**Comment by dtomcat** [comment]
I can fix it after vacation and send a pull request.  So early next week

**Comment by dtomcat** [comment]
Submitted a pull request to fix issue (#6 )

**Comment by dx4m** [comment]
Yeah, might be a typo. I have no v1.0 so the bug didn't get noticed earlier.
Have merged it. 👍
